config/routes.rb
Rails.application.routes.draw do
  get 'collaborator/index'

  devise_for :users

  resources :wikis do
    resources :collaborators
    post :create_collaborators
    delete :destroy_collaborators
  
end

  resources :charges, only: [:new, :create]
  put 'downgrade' => 'charges#downgrade'
  get 'welcome/index'

  root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis, through: :collaborators
  has_many :collaborators

  def standard?
    role == 'standard'
  end

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end

  def downgrade_wikis
    self.wikis.each do |wiki|
      wiki.update_attributes(private: false)
    end
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :users, through: :collaborators
  has_many :collaborators

  default_scope { order('created_at DESC')}

  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true

  def all_collaborators
    names = []
    collaborators.each do |collaborator|
      names << collaborator.user.name || collaborator.user.email
    end
      names
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Premium Membership - #{current_user.email}",
      amount: 10000
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken],
      plan: 'premium'
    )

    # charge = Stripe::Charge.create(
    #   customer: customer.id,
    #   amount: 10000,
    #   description: "Blocipedia Premium Membership - #{current_user.email}",
    #   currency: 'usd'
    # )
    current_user.update_attributes(stripe_id: customer.id, role: 'premium')

    flash[:success] = "Thanks for joining our premium mebership, #{current_user.email}!"
    redirect_to root_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

  def downgrade
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    sub = customer.subscriptions.first.delete
    current_user.update_attributes(role: "standard", stripe_id: nil)
    current_user.downgrade_wikis
    redirect_to root_path
  end
end

app/controllers/collaborator_controller.rb
class CollaboratorController < ApplicationController
  def index
    @collaborators = Collaborators.all
  end

  def show
    @collaborator = Collaborator.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create_collaborators
    wiki = Wiki.find(params[:wiki_id])
    params[:users].each do |user|
      # check if there is  collaborator obj for user
      Collaborator.where(wiki: wiki, user: User.find(user.to_i)).first_or_create
    end
    redirect_to wiki
  end

  def destroy_collaborators
    wiki = Wiki.find(params[:wiki_id])
    collaborator = Collaborator.find(params[:collaborator])
    collaborator.destroy
    redirect_to wiki
  end

  def create
    @wiki = Wiki.new( wiki_params )
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Great success!"
      redirect_to @wiki
    else
      flash[:error] = "Maybe you should take up a new hobby... like knitting!"
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes( wiki_params )
      flash[:notice] = "Great update success!"
    else
      flash[:error] = "You're not very good at this, are you?"
    end
    redirect_to @wiki
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "This wiki is no more! It has ceased to be!"
      redirect_to wikis_path
    else
      flash[:error] = "You cannot kill what you did not create!"
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborator_helper.rb
module CollaboratorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click Here</h4>
  <script class="stripe-button" src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>"></script>
<% end %>  

app/views/collaborator/index.html.erb
<h1>Collaborator#index</h1>
<p>Find me in app/views/collaborator/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div class="navbar navbar-inverse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Index", wikis_path %></li>
      <li><%= link_to "New Wiki", new_wiki_path %></li>
        <% if current_user && current_user.stripe_id.nil? %>
          <li><%= link_to "Upgrade!", new_charge_path %></li>
          <% else %>
          <li><%= link_to "Downgrade... Loser", downgrade_path, method: :put %>
        <% end %>
      <li><form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search!">
        </div>
          <button type="submit" class="btn btn-default">Go!</button>
        </div>
      </form>
      </li>
    </ul>
  <div class="navbar-text navbar-right" id="whodat">
    <% if current_user %>
      Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %> or
      <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

<%= yield %>

</div>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>
<p>Where Wikis Run Wild!</p>

app/views/wikis/_form.html.erb
    <div class="form-group">
      <%= form_for @wiki do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Wiki Title Here" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Talk about what you want' %>
        </div>
        <% if current_user.role == 'admin' || current_user.role == 'premium' %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          </div>
        <% end %>
        </div>
     <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= render partial: 'wikis/form', locals: { wiki: @wiki } %>
  </div>
</div>

<% if true %>
  <div class="form-group">
    <%= form_tag wiki_create_collaborators_path(@wiki) do %>
      <% users_array = User.all.map { |u| [u.name, u.id]} %>
      <%= select_tag('users', options_for_select(users_array, :selected => params[:users]), multiple: true) %>
      <%= submit_tag('Add Collaborator', name: 'collaborators[submit]') %>
    <% end %>
  </div>
<% end %>

app/views/wikis/index.html.erb
<h1>Wiki List</h1>
<% @wikis.each do |wiki| %>
  <p><%= link_to (markdown_to_html wiki.title), wiki_path(wiki.id) %></p>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class="row">
  <div class="col-md-8">
    <%= render partial: 'wikis/form', locals: { wiki: @wiki} %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<p><%= markdown_to_html @wiki.body %></p>

<% if policy(@wiki).edit? %>
  <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

<% if policy(@wiki).destroy? %>
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
<% end %>

<h2>Collaborators</h2>
<% @wiki.collaborators.each do |collaborator| %>
<p>
  <%= collaborator.user.name %>
  <%= link_to "Remove Collaborator", wiki_destroy_collaborators_path(@wiki, {collaborator: collaborator.id}), method: :delete %>
</p>
<% end %>